
-- Explicitly add ALL columns that match processor 3.0 expects
ALTER TABLE public.player_rating_history 
ADD COLUMN IF NOT EXISTS positive_votes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS negative_votes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS neutral_votes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS votes_up INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS votes_down INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS vote_score NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS vote_impact NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS result_impact NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS event_impact NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS goal_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS yellow_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS red_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS participation_multiplier NUMERIC DEFAULT 1,
ADD COLUMN IF NOT EXISTS expected_score NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_score NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS raw_delta NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS final_delta NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_mvp BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS mvp_score NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS mvp_bonus NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS rating_version TEXT DEFAULT '3.0',
ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ DEFAULT NOW();

-- Create a dummy table to force a schema cache reload in PostgREST
CREATE TABLE IF NOT EXISTS public._postgrest_reload_dummy (id int);
DROP TABLE public._postgrest_reload_dummy;
